name: Playwright Tests
on:
  pull_request:
    paths: [ package.json ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      k3s_version:
        description: k3s_version "v1.25.5+k3s2" or "v1.24"
        default: v1.24.9+k3s2
        type: string
        required: true
      keep_env:
        description: keeps the env running if not empty
        required: false
        default: ""
defaults:
  run:
    working-directory: tests
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    -
      uses: AbsaOSS/k3d-action@v2.4.0
      name: "Create Kubernetes cluster"
      with:
        cluster-name: ${{ github.repository_owner }}-ghactions-cluster
        args: "--agents 1 --image rancher/k3s:v1.24.9-k3s2"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        pwd
        npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test installation
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
